# docker-compose.yml
version: '3.8'

services:
  flow-test:
    build: .
    container_name: flow-test-engine
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    # Instala deps, builda, executa testes (com args opcionais) e gera relatório
    command: sh -lc "npm ci && npm run build && node dist/cli.js ${FLOW_TEST_ARGS:---simple} && node dist/report-generator/cli.js results/latest.json"
    environment:
      - NODE_ENV=test
      - FLOW_TEST_HTTPBIN_URL=http://httpbin
    depends_on:
      httpbin:
        condition: service_healthy
    networks:
      - flow-test-network

  # Removed mock-server; standardizing on httpbin

  httpbin:
    image: kennethreitz/httpbin
    container_name: flow-test-httpbin
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost/status/200')"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 2s
    networks:
      - flow-test-network

networks:
  flow-test-network:
    driver: bridge
