# docker-compose.yml

services:
  flow-test:
    build: .
    container_name: flow-test-engine
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    # Instala deps, builda e executa testes (com args opcionais). O relatório JSON ficará em results/latest.json
    command: sh -lc "sleep 10 && npm ci && npm run build && node dist/cli.js ${FLOW_TEST_ARGS:---simple}"
    environment:
      - NODE_ENV=test
      - FLOW_TEST_HTTPBIN_URL=http://httpbin
      - HTTPBIN_URL=http://httpbin
    depends_on:
      - httpbin
    networks:
      - flow-test-network

  # Removed mock-server; standardizing on httpbin

  httpbin:
    image: kennethreitz/httpbin
    platform: linux/amd64
    container_name: flow-test-httpbin
    ports:
      - "8080:80"
    networks:
      - flow-test-network

networks:
  flow-test-network:
    driver: bridge
