project_name: Flow Test Demo Project
test_directory: ./
globals:
  # Arquivos .env para carregar automaticamente
  # Carrega variáveis de ambiente antes da execução dos testes
  # Arquivos são carregados em ordem, últimos sobrescrevem os primeiros
  env_files:
    - .env                # Variáveis gerais
    - .env.local          # Sobrescritas locais (adicionar ao .gitignore)
    # - .env.test         # Específico para testes
    # - .env.production   # Produção (usar com cuidado)

  variables:
    api_base_url: http://localhost:8080
    httpbin_url: http://localhost:8080
    execution_mode: sequential
    default_timeout: 30000
  timeouts:
    default: 60000
    slow_tests: 120000
discovery:
  patterns:
    - '**/*.yaml'
    - '**/*.json'
    - '**/tests/**/*.yaml'
    - '**/tests/**/*.json'
    - '**/tests/*.yaml'
    - '**/tests/*.json'
  exclude:
    - '**/temp/**'
    - '**/node_modules/**'
    - '**/flows/**'
    - '**/results/**'
    - '**/dist/**'
priorities:
  levels:
    - critical
    - high
    - medium
    - low
  required:
    - critical
    - high
  fail_fast_on_required: false
execution:
  mode: sequential
  max_parallel: 3
  timeout: 60000
  continue_on_failure: true
  retry_failed:
    enabled: true
    max_attempts: 2
    delay_ms: 2000
reporting:
  formats:
    - json
    - html
  output_dir: ./results
  aggregate: true
  include_performance_metrics: true
  include_variables_state: true
