# Flow Test Engine v2.0 Configuration
project_name: "Flow Test Demo Project"
test_directory: "./"

# Global variables and settings
globals:
  variables:
    api_base_url: "http://localhost:8080"
    httpbin_url: "http://localhost:8080"
    default_timeout: 30000
  timeouts:
    default: 30000
    slow_tests: 60000

# Test discovery settings
discovery:
  patterns:
    - "**/tests/*.yaml"
  exclude:
    - "**/temp/**"
    - "**/node_modules/**"
    - "**/flows/**"

# Priority system configuration
priorities:
  levels: ["critical", "high", "medium", "low"]
  required: ["critical", "high"]
  fail_fast_on_required: false

# Execution settings
execution:
  mode: "sequential"  # ou "parallel"
  max_parallel: 3
  timeout: 30000
  continue_on_failure: true
  retry_failed:
    enabled: false
    max_attempts: 2
    delay_ms: 1000

# Reporting configuration
reporting:
  formats: ["html", "json"]
  output_dir: "./results"
  aggregate: true
  include_performance_metrics: true
  include_variables_state: true