# Flow Test Engine Configuration - Debug Mode
project_name: "Flow Test Debug Mode"
test_directory: "./"

# Global variables and settings
globals:
  variables:
    api_base_url: "http://localhost:8080"
    httpbin_url: "http://localhost:8080"
    debug_mode: true
    verbose_logging: true
    default_timeout: 60000
  timeouts:
    default: 120000     # Longer timeouts for debugging
    slow_tests: 300000  # Very long for debugging

# Test discovery settings
discovery:
  patterns:
    - "**/*.yaml"
    - "**/tests/**/*.yaml"
    - "**/tests/*.yaml"
  exclude:
    - "**/temp/**"
    - "**/node_modules/**"
    - "**/flows/**"
    - "**/results/**"
    - "**/dist/**"

# Priority system configuration
priorities:
  levels: ["critical", "high", "medium", "low"]
  required: ["critical", "high"]
  fail_fast_on_required: false  # Don't fail fast in debug mode

# Execution settings for debugging
execution:
  mode: "sequential"  # Sequential for easier debugging
  max_parallel: 1
  timeout: 120000     # Long timeout for debugging
  continue_on_failure: true  # Continue to see all failures
  retry_failed:
    enabled: false    # No retries when debugging

# Reporting configuration with maximum detail
reporting:
  formats: ["html", "json"]
  output_dir: "./results"
  aggregate: true
  include_performance_metrics: true
  include_variables_state: true
  debug_detail: true
  verbose_logging: true