# Flow Test Engine Configuration - Performance Testing
project_name: "Flow Test Performance Testing"
test_directory: "./"

# Global variables and settings
globals:
  variables:
    api_base_url: "http://localhost:8080"
    httpbin_url: "http://localhost:8080"
    performance_mode: true
    default_timeout: 30000
    max_response_time: 1000
    concurrent_users: 10
  timeouts:
    default: 30000      # Shorter timeouts for performance testing
    slow_tests: 60000

# Test discovery settings - Focus on performance tests
discovery:
  patterns:
    - "**/performance*.yaml"
    - "**/load*.yaml"
    - "**/stress*.yaml"
    - "**/*performance*.yaml"
  exclude:
    - "**/temp/**"
    - "**/node_modules/**"
    - "**/flows/**"
    - "**/results/**"
    - "**/dist/**"

# Priority system configuration for performance
priorities:
  levels: ["critical", "high", "medium", "low"]
  required: ["critical", "high"]
  fail_fast_on_required: true  # Fail fast for performance issues

# Execution settings optimized for performance testing
execution:
  mode: "parallel"
  max_parallel: 10    # Higher concurrency for load testing
  timeout: 30000      # Shorter timeout
  continue_on_failure: false  # Stop on performance failures
  retry_failed:
    enabled: false    # No retries in performance tests

# Reporting configuration for performance analysis
reporting:
  formats: ["html", "json"]
  output_dir: "./results"
  aggregate: true
  include_performance_metrics: true
  include_variables_state: false  # Reduce overhead
  performance_focus: true