# Flow Test Engine Configuration - Sequential Only Mode
project_name: "Flow Test Sequential Execution"
test_directory: "./"

# Global variables and settings
globals:
  variables:
    api_base_url: "http://localhost:8080"
    httpbin_url: "http://localhost:8080"
    execution_mode: "sequential"
    default_timeout: 30000
  timeouts:
    default: 60000
    slow_tests: 120000

# Test discovery settings
discovery:
  patterns:
    - "**/*.yaml"
    - "**/tests/**/*.yaml"
    - "**/tests/*.yaml"
  exclude:
    - "**/temp/**"
    - "**/node_modules/**"
    - "**/flows/**"
    - "**/results/**"
    - "**/dist/**"

# Priority system configuration
priorities:
  levels: ["critical", "high", "medium", "low"]
  required: ["critical", "high"]
  fail_fast_on_required: false

# Execution settings - SEQUENTIAL ONLY
execution:
  mode: "sequential"  # Force sequential execution
  max_parallel: 1     # Only one test at a time
  timeout: 60000
  continue_on_failure: true
  retry_failed:
    enabled: true
    max_attempts: 2
    delay_ms: 2000

# Reporting configuration optimized for sequential execution
reporting:
  formats: ["html", "json"]
  output_dir: "./results"
  aggregate: true
  include_performance_metrics: true
  include_variables_state: true
  sequential_timing: true  # Track sequential execution timing