import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Autogenerate sidebar from the filesystem structure under ../docs
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;

