import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Generate a single API sidebar including both manual API index and auto docs
const sidebars: SidebarsConfig = {
  apiSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;

